# added here free defined functions to generate email addresses based on different domains. Each function takes a username and an optional domain parameter (with a default value) and returns the formatted email address. The build_email function is a higher-order function that takes a username and an email function as arguments and calls the email function with the username to generate the email address.

def gmail_email(username, domain='gmail.com'):
    return f"{username}@{domain}"

def yahoo_email(username, domain='yahoo.com'):
    return f"{username}@{domain}"

def hotmail_email(username, domain='hotmail.com'):
    return f"{username}@{domain}"

def example_email(username, domain='example.com'):
    return f"{username}@{domain}"


def build_email(username, email_function):
    return email_function(username) # Call the email function with the username to get the email address generated by the email function "gmail_email("john.doe") => john.doe@gmail.com"

print(build_email("kamalm", gmail_email))  # Output: kamalm@gmail.com
print(build_email("johnsmith", hotmail_email))  # Output: johnsmith@hotmail.com
print(build_email("alice", yahoo_email))  # Output: alice@yahoo.com
print(build_email("bob", example_email))  # Output: bob@example.com
